### ISSUE TITLE
[ESTRUTURA] - Acesso aos servidores CMC

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#11]
**Descrição do Problema**

Conforme definido através reunião 27/03/2020, precisamos acessar remotamente os servidores (LDAP e BD) para conseguirmos rodar remotamente o backend da aplicação.

**Para Reproduzir**

Não se aplica

**Comment by aleodoni** [comment]
@DePorto, pelo que você colocou, não há possibilidade de acesso aos servidores via vpn, correto ?
Caso afirmativo, peço que você feche esta issue pois teremos que trabalhar em outra solução.
Vou assinalar essa issue para você.

**Comment by brunosoli** [comment]
Com relação ao banco, não é melhor criar os migrations para permitir rodar o banco localmente num docker?
Vou pensar em algo quanto ao LDAP (um docker ou um mock).

**Comment by brunosoli** [comment]
Isto resolve o LDAP:

```shell
sudo docker run -p 389:389 -p 636:636 --name cmc-openldap --detach \
--env LDAP_ORGANISATION="CMC" --env LDAP_DOMAIN="cmc.pr.gov.br" \
--env LDAP_ADMIN_PASSWORD="senha" --env LDAP_READONLY_USER="true" \
--env LDAP_READONLY_USER_USERNAME="user" \
--env LDAP_READONLY_USER_PASSWORD="senha" --detach osixia/openldap
```

**Comment by aleodoni** [comment]
> Com relação ao banco, não é melhor criar os migrations para permitir rodar o banco localmente num docker?

@brunosoli, essa é uma das opções; já tinha levantado isso há um tempo atrás com o Rodrigo, mas além disso, deveriam ser criadas migrations e seeds pra simular as views da elotech bem como toda a configuração para gerar esses caras.

Essa, na minha opinião seria o processo mais correto, pq além de tudo já abre o caminho pra rodar os testes e a integração contínua.

Mas tudo isso obviamente demanda mais trabalho e mais tempo pra que seja feito.

Também acho melhor discutirmos isso numa outra issue, caso a gente siga para este caminho; esta aqui provavelmente será fechada porque não seguiremos por este caminho.

**Comment by DePorto** [comment]
Vamos desconsiderar a opção de acesso aos servidores da CMC via VPN. 
Este recurso não vai funcionar a contento.
Podemos pensar em criar uma VPN entre as estações de trabalho dos envolvidos no projeto, parece-me que há esta possibilidade. Não seria algo a considerar?
Assim, teoricamente, poderíamos ter uma instância apenas rodando o BD e os demais envolvidos acessariam o serviço. Qualquer mudança no andar do projeto nas circunstâncias que nos encontramos poderia ser anotada (migration?) e estaria disponível para os demais.
Acredito que escolhendo essa possiblidade, também seja o caso de se encaminhar o andamento disso em outra issue.
Aguardo retorno de vocês.

**Comment by rodrigoferraro** [comment]
Parece que, embora seja um trabalho a mais, talvez seja o certo a se fazer...
As vezes não se tem "scappatoia ne acorciatoia" como diziam meus camaradas fascistas.. sem escapatória ou atalho. 
Vamos fazer esse docker do postgres?
Se precisar, estou todos os dias na CMC.

Vocês que mandam...

**Comment by aleodoni** [comment]
Não acho que seja uma boa ideia fazer vpn entre desenvolvedores. Vamos estar propensos aos mesmos problema, por exemplo conexão ruim, máquina fora do ar, etc.

O ideal é que cada desenvolvedor não dependa de outra estrutura pra poder trabalhar.

Vou fechar essa issue e abrir outra com as possibilidades.
