### ISSUE TITLE
[NEW FEATURE] - Login no Sistema

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#12]
**O que você gostaria de adicionar**:

Acesso e permissões dos usuários no sistema.

**Por que isso é necessário ?**:

Para que os usuários acessem o sistema e possam executar as ações correspondentes ao setor que estiverem lotados.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Não

**Contexto Adicional**

**Requisito 1**
A validação usuário/senha será feita através conta LDAP

**Requisito 2**
Informações referentes ao usuário serão buscadas no LDAP :
1. usuario 
2. email
3. nome_usuário (nome completo)

**Requisito 3**
Informações referentes ao usuário serão buscadas no Sistema :
1. setor_usuário (id do setor)
2. area_usuario (id da área)
3. nome_setor_usuario (nome do setor)
4. nome_area_usuario (nome da área)

**Requisito 4**
Sistema deverá gerar token de autenticação com informações do usuário (padrão)

**Comment by rodrigoferraro** [comment]
Requisito 1
- existe esse novo caso que tomamos conhecimento agora, de IPMC manifestar-se em processo específico. Como alguém de fora pode fazer login no sistema SE a validação é no LDAP?
    - teria como criar usuários no LDAP que não vem do sistema de RH? 
        - (pelo que me lembro de Bruno falando, sim). Pra isso teria de ser criado um processo que faça esse integração!
        - tem que estar preparado para outros casos... quanto mais aberto para acolhimento e integração, melhor o sistema...
        - inicialmente podemos usar aquele docker do openLDAP que Bruno passou, e inserir as informações "hardcoded" mesmo.

** ressalto que não estou trazendo trabalhos desnecessários.. acho que só devemos conversar, e pensar em deixar a estrutura preparada, podendo usar mocks, fakes, etc para suprir a necessidade inicial **

**Comment by rodrigoferraro** [comment]
Requisito 2
Dados referentes à lotação do usuário serão buscados no sistema de RH - Elotech (a confirmar)

- eu acho melhor desacoplar da Elotech. (complemento do Requisito 1)
    - melhor trazer as informações necessárias para o LDAP.
    - acredito que a melhor forma de não dependermos de um sistema não confiável, é isolá-lo.
        - um procedimento de sincronização semi automático, supervisionado.
        - um programa a parte. Com um mínimo de inteligência capaz de identificar quando ocorrerá atualização de dados.
        - quando atualização identificada, deve requerer aprovação de pessoa responsável.
        - não querendo implementar um json-server pra isso, dá pra simplesmente usar os dados do LDAP aceitando que a sincronização está feita, e os dados estão corretos.

** ressalto que não estou trazendo trabalhos desnecessários.. acho que só devemos conversar, e pensar em deixar a estrutura preparada, podendo usar mocks, fakes, etc para suprir a necessidade inicial **

**Comment by rodrigoferraro** [comment]
Requisito 3
Sistema deverá gerar token de autenticação com informações do usuário

- Esse token já vem integrando no payload as informações que interessam para as verificações de permissão (quando necessárias) SEM precisar consultar novamente o LDAP ou Elotech?
    - pelo pouco que entendi das aulas até agora, isso é o mais apropriado, sim/não?

**Comment by brunosoli** [comment]
> * existe esse novo caso que tomamos conhecimento agora, de IPMC manifestar-se em processo específico. Como alguém de fora pode fazer login no sistema SE a validação é no LDAP?
>   
>   * teria como criar usuários no LDAP que não vem do sistema de RH?
>     
>     * (pelo que me lembro de Bruno falando, sim). Pra isso teria de ser criado um processo que faça esse integração!
>     * tem que estar preparado para outros casos... quanto mais aberto para acolhimento e integração, melhor o sistema...

Sobre IPMC e acessos externos, há de se considerar que haverá uma divisão de protocolo que poderá receber as manifestações e juntar ao processo. Senão você assume que o terceiros interessados deverão saber o número do processo e usar o sistema.

Quanto aos logins, com a portaria 466/2019 atualizada é possível a criação de login para terceiros.

**Comment by rodrigoferraro** [comment]
> Senão você assume que o terceiros interessados deverão saber o número do processo e usar o sistema.

vejo um diferencial de valor real ser capaz de integrar de maneira mais eficiente, aqueles que colaboram, de alguma forma, para o andamento dos trabalhos de uma organização.
Considero valorização do tempo de cada um.
Se o fornecedor, ao invés de imprimir um monte de folhas e trazer fisicamente na Câmara, puder entrar em nosso sistema e anexar os documentos de maneira transparente, poupando esforço a todos os interessados, isso me parece bom.
Se o IPMC pode fazer o mesmo, isso me parece muito bom
Se qualquer um puder fazer o mesmo, claro... com todas as medidas para assegurar integridade e confiabilidade das informações... por que não?

** ressalto que não estou trazendo trabalhos desnecessários.. acho que só devemos conversar, e pensar em deixar a estrutura preparada. Ainda que façamos somente o MVP, vamos pensar grande. Backlog é pra isso né... mas a estrutura tem de ser construída para suportar as melhorias futuras **

**Comment by rodrigoferraro** [comment]
Quanto aos logins, com a portaria 466/2019 atualizada é possível a criação de login para terceiros.

aí só precisamos definir o procedimento de atualização disso.. por exemplo, quando o usuário do IPMC sai de férias, seu substituto deve ter acesso tbm.. só pra citar um exemplo do que consistiria esse procedimento de atualização de usuários externos...

**Comment by rodrigoferraro** [comment]
>     * Esse token já vem integrando no payload as informações que interessam para as verificações de permissão (quando necessárias) SEM precisar consultar novamente o LDAP ou Elotech?
>       
>       * pelo pouco que entendi das aulas até agora, isso é o mais apropriado, sim/não?

acabei de ver no código do LoginController que já carrega as informações no jwt.
mas com a visão restrita que tenho de todo o código, até agora, não consigo ainda ter certeza que não consulte mais LDAP ou Elotech para realizar todas as outras operações no sistema.

**Comment by brunosoli** [comment]
> vejo um diferencial de valor real ser capaz de integrar de maneira mais eficiente, aqueles que colaboram, de alguma forma, para o andamento dos trabalhos de uma organização.
> Considero valorização do tempo de cada um.

Concordo.
Sei que isso não entra no MVP e por isso cabe bastante conversa. Numa dessa um serviço de SSO pra gerenciar os acessos seja uma opção.

**Comment by rodrigoferraro** [comment]
> 
> 
> > vejo um diferencial de valor real ser capaz de integrar de maneira mais eficiente, aqueles que colaboram, de alguma forma, para o andamento dos trabalhos de uma organização.
> > Considero valorização do tempo de cada um.
> 
> Concordo.
> Sei que isso não entra no MVP e por isso cabe bastante conversa. Numa dessa um serviço de SSO pra gerenciar os acessos seja uma opção.

Já é um avanço na discussão... 
vamos lembrar que o fato de precisar conversar muito sobre um assunto não significa que temos a eternidade pra decidir..

**Comment by fderosso** [comment]
Então seria o seguinte?
1) Login pelo LDAP, independente se for criar um login para alguém do IPMC, se login ok vou retornar somente o login, o nome e o email da pessoa.
2) Vamos ter no sistema sua própria tabela de Setores, que poderá ser atualizada caso haja necessidade pelos dados da elotech.
3) Vamos ter no sistema sua própria tabela de lotações, baseado na tabela própria de Setores e no login da pessoa no LDAP.
4) Além de token para autenticação temos tabelas de permissões conforme a área que pertence a pessoa(o menu é assim), se guardarmos dentro do payload essas informações constantemente teremos que abrir o token para acessá-las, no momento essas informações são guardadas no sessionStorage do browser, a hora que o usuário fecha a aba essas informações são descartadas. 

Vamos definir estas coisas para eu poder ir implementando novamente aqui, vou mexer em estruturas e criar tabelas novas eu acho, estou usando um postgres local, para não mexer em configurações de banco, mas nada impede de outras pessoas adaptarem um json_server, deixando a mesma estrutura para todos.

**Comment by aleodoni** [comment]
Pessoal, vamos tentar focar apenas no cerne da issue, senão ela vai ficar gigante e com informações que não são pertinentes à mesma. 

Aqui temos que ser diretos e "compactos". 

Vou atualizar os requisitos iniciais para que a gente tenha um só lugar pra olhar.

**Comment by fderosso** [comment]
Ok, o que o Alexandre definir como requisitos iniciais vou implementar aqui, sempre repassando o que eu criar de estrutura aqui para ele.

**Comment by aleodoni** [comment]
Testado com os containers docker LDAP e Postgres. Único problema que encontrei no docker do LDAP foi que dando um bind com um usuário sem ser o **admin** a pesquisa não retorna nada.

Adicionei uma gambiarra no LoginController. Ele faz um bind com o usuário passado na tela de login para validar o mesmo e depois faz outro bind com o admin do LDAP pra fazer a pesquisa.

Depois a gente ajusta esses probleminhas; talvez criar uma issue para isso. Essa eu tô fechando.

**Comment by aleodoni** [comment]
Atualização final da issue. Conversando com o @brunosoli, decidimos utilizar o usuário authproxy para fazer a pesquisa no LDAP. Essa é a maneira correta de fazer a pesquisa no LDAP e não utilizando o próprio usuário de login.
Alteração feita no código, testada e OK.
