### ISSUE TITLE
[MELHORIA TÉCNICA] - Migrations e seeds tabelas login do sistema

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#19]
**O que você gostaria de adicionar**:

Migrations para as tabelas relacionadas com o login do sistema

**Por que isso é necessário ?**:

Para manter um versionamento das tabelas que fazem parte do login, para facilitar a manutenção das mesmas e também facilitar a criação do banco localmente.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Não

**Contexto Adicional**

Não se aplica.

**Comment by aleodoni** [comment]
Testado e inicialmente funcionando; precisamos depois verificar as migrations para consolidar constraints, etc.

**Comment by rodrigoferraro** [comment]
ué.. não entendi! 
em que pasta estão as migrations?

**Comment by aleodoni** [comment]
> ué.. não entendi!
> em que pasta estão as migrations?

Como dito no Rainbow: O commit será feito dia 09/05 para não quebrar outras coisas.
