### ISSUE TITLE
[ESTRUTURA] - Docker com LDAP e seeds

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#20]
**O que você gostaria de adicionar**:

Criar configuração docker para subir LDAP localmente

**Por que isso é necessário ?**:

Para poder rodar a aplicação localmente e também proporcionar a execução de testes e CI

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Sim, hoje não é possível rodar a aplicação localmente sem depender de servidores externos (LDAP)

**Contexto Adicional**

Deve-se também criar arquivo ldif com grupos e usuários para popular o LDAP

**Comment by brunosoli** [comment]
Essa está comigo.
Posso criar um conjunto genérico de usuários e grupos ou vocês tem alguma preferência?

**Comment by aleodoni** [comment]
Por mim pode criar um genérico. 
Outra coisa, já tem um docker-compose.yml criado no backend com o postgres; pode adicionar o LDAP lá.
