### ISSUE TITLE
Criação de crud para setor

### ISSUE THREAD

**Issue by fderosso** [CMCuritiba/processo_eletronico#21]
Criar uma tela crud de cadastro de setores, para facilitar o cadastro.

**Necessidade**:

Com esta tela o a manutenção de setores no sistema ficará mais ágil, possibilitando a área de informática, a princípio, gerenciar os setores cadastrados no sistema.

**Comment by fderosso** [comment]
Acabei de commitar lá a tela de crud de setores, tem que modificar no banco as seguintes coisas:
1) dar esse grant, se precisar:

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE spa2.setor TO "usuario.spa2";

2) criar a sequence:

CREATE SEQUENCE spa2.setor_set_id_seq
    START WITH 552
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
GRANT ALL ON SEQUENCE spa2.setor_set_id_seq TO spa2;
GRANT ALL ON SEQUENCE spa2.setor_set_id_seq TO "usuario.spa2";

3) colocar no campo "set_id" da tabela "setor" o default: 

nextval('spa2.setor_set_id_seq'::regclass)

4) o campo set_inativacao está inútil, depois vamos apagar ele

5) nas tabelas spa2.menu e spa2.tela inserir os registros, para aparecer no menu:

insert into spa2.tela(tel_id, tel_nome) values(624,'Setores');

insert into spa2.menu(men_id, men_id_pai, men_nome, men_url, tel_id, mmu_id, men_ordem_pai, tel_interna) values (527, 43, 'Setores', '/setores', 624, 1, null, false);

*** Queria saber se já fecho a issue ou somente quando for testada por mais alguém, se for o caso como o projeto está no começo eu fecho a issue e abrimos depois outra para validação/homologação.

**Comment by aleodoni** [comment]
@fderosso, pode fechar; depois a gente pode abrir outra pra homologar.

**Comment by fderosso** [comment]
Fechando a issue, implementado e posteriormente homologado.
