### ISSUE TITLE
[BUG] Conexão segura ao backend

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/processo_eletronico#295]
# Descrição do Bug

Hoje o backend possui configuração de certificado e chave para acesso segura à API. O ideal é a aplicação utilizar apenas uma porta e não precisar gerenciar conexões seguras, terceirizando essa responsabilidade para um proxy externo (nginx ou apache, por exemplo).

Vide:
https://github.com/CMCuritiba/processo_eletronico/blob/6fdd41fc3bfbe3fe79d3c6b59f3d70827cbea44d/backend/src/server.js#L5

## Para Reproduzir

Passos para reproduzir o bug:
1. Vá para `backend`
1. "Rode" a aplicação e tente acessar a API com HTTPS no Firefox, por exemplo.

## Comportamento Esperado

O frontend deve acessar a API no backend através de conexão HTTPS gerenciada fora do backend por um proxy externo (nginx ou apache, por exemplo).

## Exceção ou Erro

**TODO**: adicionar erro do Firefox aqui.

## Screenshots

Não se aplica.

## Contexto Adicional

Talvez seja interessante adicionar um container do nginx no [docker-compose.yml](../blob/develop/backend/docker-compose.yml) do backend para facilitar o fluxo de desenvolvimento.

## Testes de regressão

TODO: adicionar teste de regressão, se aplicável.

**Comment by brunosoli** [comment]
Apesar do código fonte do backend utilizar os certificados, a infra de contêineres adicionada em #305 não depende de sua utilização (inclusive não expõe portas para conexão HTTPS nos contêineres nginx). Desta forma, a remoção dos certificados do código é segura (recomendando apenas a utilização de um proxy reverso externo à aplicação para acesso HTTPS ao backend).

**Comment by aleodoni** [comment]
@wehmhoff @DePorto @brunosoli @rodrigoferraro 
Conforme conversa com @brunosoli no dia 30/11/2020, achamos que a melhor opção (descrita acima) seria configurar o backend para usar o protocolo HTTP e fazer o proxy reverso no NGINX.
Além de ficar mais simples, deixamos cada camada responsável pela sua função.
Existia um problema em se rodar a aplicação (ambiente de desenvolvimento) no Firefox, mas testei a mesma localmente e não consegui reproduzir o problema. Abaixo prints da mesma :

![Captura de tela_2020-11-30_17-30-15](https://user-images.githubusercontent.com/12944198/100662402-9d47a900-3333-11eb-8048-d00d6b87198d.png)

![Captura de tela_2020-11-30_17-32-04](https://user-images.githubusercontent.com/12944198/100662430-a2a4f380-3333-11eb-9e39-01235b31a6fc.png)

Fico no aguardo do OK de @DePorto ou @rodrigoferraro para implementar essa solução.

**Comment by aleodoni** [comment]
@brunosoli @wehmhoff @DePorto @rodrigoferraro 
Pessoal, para não atrasar o cronograma, efetuei as alterações citadas nessa issue mesmo sem receber o OK que tinha requisitado no início da semana.
Agora, independente do ambiente, será instanciado apenas o servidor HTTP. 
Também criei os testes relacionados à issue que garantem que a solução funciona.
@brunosoli , creio que agora é só configurar o proxy reverso no nginx.
