### ISSUE TITLE
[MELHORIA] Retirar diretório __tests__ de dentro do /src

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#298]
**O que você gostaria de adicionar**:

Mover o diretório __tests__ para fora do diretório /src

**Por que isso é necessário ?**:

Para que o build do sistema não inclua os testes no processo de compilação.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Gera erro quando o build tenta compilar um teste.

**Contexto Adicional**

TODOS os testes deverão ser refatorados em relação aos imports pela mudança de diretório.

**Comment by brunosoli** [comment]
Fazendo um build do backend agora, vi também que o diretório de database, incluindo as migrations, também são inclusas quando damos o `sucrase ./src -d ./dist --transforms imports`.
Isso também precisa ser revisto, certo? Se sim, abrimos outra issue.

**Comment by aleodoni** [comment]
> Fazendo um build do backend agora, vi também que o diretório de database, incluindo as migrations, também são inclusas quando damos o `sucrase ./src -d ./dist --transforms imports`.
> Isso também precisa ser revisto, certo? Se sim, abrimos outra issue.

Não. Esse precisa ficar pois num futuro distante, as migrations serão rodadas automaticamente toda vez que for feito um merge no master/staging usando a integração contínua.

**Comment by aleodoni** [comment]
Fechando essa issue pois já fiz o commit destas alterações.
