### ISSUE TITLE
[DOC] Levantamento dos dados persistentes para gerar as seeds das tabelas de sistema

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/processo_eletronico#306]
**Descrição da issue**

Relacionar a seguir as tabelas com dados persistentes que precisam ter suas informações transcritas em seeds para garantir a cobertura de todos os dados necessários para a replicação de uma estrutura funcional para o sistema.

**Exemplo de uso**

Seeds dos dados das tabelas de tipos de trâmites e dos fluxos.

Sugiro que o time @CMCuritiba/processo-eletronico reveja esses dados em conjunto. Do levantamento para a transcrição em seeds.

Favor relacionar abaixo a lista de itens a serem verificados para registro do trabalho realizado, para posterior referência.

@FabioDerossoTeixeira aguardamos a relação das tabelas para que sejam levantados os dados a serem transcritos.

**Comment by aleodoni** [comment]
@DePorto , como comentado no bolha, acredito que só o @FabioDerossoTeixeira tenha conhecimento dessa informação. Fábio, quando puder, por favor, adicione nesta issue as tabelas, campos e valores que são necessários para que possamos criar as suas seeds.
Pode ser um dump mesmo do banco com tabela e valores, sem problemas.

**Comment by fderosso** [comment]
A principio as tabelas são: area_menu, banco, fluxo, genero, menu, modelo_menu, nodo, proximo_tramite, razao_tramite, tela, tipo_documento, tipo_manifestacao, tipo_processo.
Vou passar o dump no decorrer da semana, pois estou alterando os dados a pedido do RH.

**Comment by aleodoni** [comment]
Vou revisar os seeds das seguintes tabelas e usar como base o último dump que o @FabioDerossoTeixeira me passou
- area_menu
- banco
- fluxo
- genero
- menu
- modelo_menu
- nodo
- proximo_tramite
- razao_tramite
- tela
- tipo_documento
- tipo_manifestacao
- tipo_processo

**Comment by aleodoni** [comment]
Criadas e testadas as seeds para as tabelas relacionadas acima.
