### ISSUE TITLE
[DOC] Parâmetros de conexão LDAP

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/processo_eletronico#31]
**Descrição da issue**

Sugiro a alteração nas variáveis de ambiente, em [backend/.env.example](../blob/develop/backend/.env.example), de alguns parâmetros pra conexão com o LDAP. Mais especificamente para melhor parametrizar as árvores de usuários e grupos, bem como o filtro de usuários e grupos.

A `LDAP_URL` não precisa ter porta, podemos assumir que as conexões do tipo `ldap://` utilizam a porta 389 e as conexões `ldaps://` usam a porta 636 para conexões seguras.

Como é esperada uma atualização no serviço de LDAP no decorrer da implantação do processo eletrônico, a parametrização será útil e caso haja alteração nos DNs não será necessária alteração em código (parametrizado >> _hardcoded_).

Outro ponto, o filtro de usuários e grupos pode servir pra diferenciar usuários em tempo de autenticação (antes da autorização). Por exemplo, diferenciando usuários de sistema ou apenas usuários que possuam matrícula, terceiros, etc (independente de lotação). O mesmo vale para grupos.

**Exemplo de uso**

O `.env` conteria:

```
# Conexao LDAP
LDAP_URL=
LDAP_USERS_OU=
LDAP_GROUPS_OU=
LDAP_BIND_USER=
LDAP_BIND_PASS=
LDAP_USER_FILTER=
LDAP_GROUP_FILTER=
```

Uma configuração de exemplo:
```
# Conexao LDAP
LDAP_URL=ldap://localhost
LDAP_USERS_OU=ou=usuarios,dc=exemplo,dc=com,dc=br
LDAP_GROUPS_OU=ou=grupos,dc=exemplo,dc=com,dc=br
LDAP_BIND_USER=cn=bind,dc=exemplo,dc=com,dc=br
LDAP_BIND_PASS=bindpass
LDAP_USER_FILTER=(employeeNumber=*)
LDAP_GROUP_FILTER=(objectClass=groupOfNames)
```

**Comment by brunosoli** [comment]
Apesar do filtro de grupos funcionar exatamente da mesma forma que o de usuários, só será possível validá-lo quando o aplicativo usar os grupos do LDAP.

**Comment by rodrigoferraro** [comment]
> 
> 
> Apesar do filtro de grupos funcionar exatamente da mesma forma que o de usuários, só será possível validá-lo quando o aplicativo usar os grupos do LDAP.

Eu ainda não consegui entender como é que esse user_filter || group_filter funciona, e como, praticamente, impacta no sistema.
Eu sei que eu poderia ir no youtube e assistir alguns videos, desde o básico de LDAP até como utilizar user_filter, etc.. mas não to afim não.. você pode me explicar?

**Comment by brunosoli** [comment]
A base de usuários no LDAP possui vários tipos de  usuários: efetivos, comissionados, terceiros, de sistema e virtuais (genéricos, impersonificados e tal, como `deprole`, `rh`, etc).
O filtro de usuários pode ser usado para separar esses tipos, por exemplo. Podemos fazer qualquer tipo de filtro que precisemos, só usuários que tenham e-mail, só usuários de determinado grupo, só usuários ativos e por aí vai.
O mesmo para os grupos, podemos filtrar os grupos por suas propriedades no LDAP.
