### ISSUE TITLE
[MELHORIA] Problema com a inicialização do banco com 'migrations' e 'seeds'

### ISSUE THREAD

**Issue by wehmhoff** [CMCuritiba/processo_eletronico#318]
**Descrição do Erro**
Quando se inicia um novo banco de dados utilizando o 'sequelize', o processo é interrompido com a seguinte mensagem: 
     == 20200423190113-genero: migrating =======
     ERROR: null value in column "gen_visivel" of relation "genero" violates not-null constraint

**Para Reproduzir**
1. Crie um banco de dados vazio de acordo com as configurações do sistema (usuário, senha e banco)
2. Vá para a pasta backend do sistema 
3. Rode o comando 'yarn sequelize db:migrate'
4. Rode o comando 'yarn sequelize db:seed:all'

**Comportamento Esperado**
O comando deveria ser bem sucedido, inserindo todos os dados nas tabelas.

**Exceção ou Erro**
No log do comando

**Contexto Adicional**
Considerando-se a utlização de um banco de dados central, a tabela foi criado com uma 'migration' (20200423184607-cria-tabela-genero.js) e rodou corretamente. Depois, foi criada a 'seed' (20200423190113-genero) e foi inserida corretamente porque correspondia ao formato da tabela naquele momento. Posteriormente a tabela 'genero' foi modificada por outra migration (20201013123550-add-get_visivel-table-genero.js) com os dados já existentes.

**Comment by wehmhoff** [comment]
Atualmente não é possível rodas as seeds sem algum 'malabarismo', como remover a migration do diretório, rodar as migrations, rodar as seeds e rodar a migração restarnte depois. Qual a solução mais adequada para esse caso?

**Comment by brunosoli** [comment]
Acredito que sejam nestes ajustes de migrations e seeds que o @aleodoni esteja correndo atrás. Como a issue #306, por exemplo?

IMHO, o **ideal** é não criar coisas direto no banco, terminar as migrations e passar a fazer tudo por elas para não perder o fio da meada.

**Comment by wehmhoff** [comment]
Lamento ter que mudar o título e a descrição, mas além de perceber que o problema é um pouco mais complexo, achei melhor mudar para uma melhoria porque exige trabalho adicional com seeds e migrations.

Possível solução:
1. Rodar as migrations em 3 etapas:
- Criar uma migration com o novo campo, mas permitir valores nulos;

> module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.addColumn(‘users’, ‘active’, {
      type: Sequelize.BOOLEAN,
    });
  },
  down: queryInterface => {
    return queryInterface.removeColumn(‘users’, ‘active’);
  },
};

- Criar uma migration que atualiza os dados na tabela;
>module.exports = {
  up: queryInterface => {
    return queryInterface.sequelize.query(
      ‘UPDATE users SET  active=false ‘
    );
  },  down: queryInterface => {
    return queryInterface.sequelize.query(
      ‘UPDATE users SET active=null ‘
    );
  },
};
- Alterar a coluna para valores não-nulos
>module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.changeColumn(
      'users',
      'active',
      {
        type: Sequelize.BOOLEAN,
        allowNull: false,
        defaultValue: false,
      }
    )
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.changeColumn(
      'users',
      'active',
      {
        type: Sequelize.BOOLEAN,
      }
    );
  }
};
2. Apagar a seed original
3. Criar uma nova seed atualizada

Também é possível criar uma função que já prevê essas 3 etapas dentro de uma única migration, apesar de executar 3 operações:

> queryInterface.addColumn(
            "users",
            "active",
            {
                type   : Sequelize.BOOLEAM,
            }
        ).then(function (data) {
return queryInterface.sequelize.query(
      ‘UPDATE users SET active=false‘
    );
            }).then(function (data) {
                queryInterface.changeColumn(
                    "users",
                    "active",
                    {
                        type      : Sequelize.BOOLEAM,
                        allowNull : false
                    }
                );
            });

Essa solução preserva os dados existentes, mas também permite que novos dados seja acrescentados mais tarde.

**Comment by aleodoni** [comment]
Como o banco ainda está sofrendo várias alterações, estou criando migrations para realizar esses ajustes.
A migration que adiciona este campo já foi commitada a 11 dias atrás e pode ser encontrada em :
https://github.com/CMCuritiba/processo_eletronico/blob/develop/backend/src/database/migrations/20201013123550-add-get_visivel-table-genero.js

Uma recomendação que faço é que sempre que vocês atualizem o backend via git pull, limpem o BD e refaçam todas as migrations e seeds para ter certeza que estão com a versão mais atualizada do BD. Isso pode ser feito assim : 
```javascript
yarn sequelize db:drop
yarn sequelize db:create
yarn sequelize db:migrate
yarn sequelize db:seed:all
```
Qualquer dúvida é só me avisar.

**Comment by aleodoni** [comment]
Só um comentário a respeito das migrations/seeds : 
Como vocês podem notar, existem trocentas migrations e várias delas são relativas à alterações feitas em tabelas, triggers, functions, views, etc.
Uma opção para simplificar o processo seria alterar as migrations antigas com as atualizações. Pontos positivos:
- Fica mais simples;
- Não precisamos criar tantas migrations.
Pontos negativos:
- Perdemos o track e a documentação das alterações que são feitas no BD o que eu acho péssimo;
- Dificulta o processo de reverter uma migration

Eu preferi criar migration para cada alteração do banco pois além de seguir as boas práticas, conseguimos de maneira bem tranquila acompanhar estas alterações apesar de ser complicado criar mecanismos para revertermos as mesmas.

Por favor, fiquem à vontade para revisar a metodologia empregada e se for o caso aplicar alterações na mesma.

**Comment by wehmhoff** [comment]
@aleodoni , as migrations estão todas corretas e não apresentaram problemas. O problema era uma seed que não continha o campo 'gen_visível' e causava um erro de inserção no momento de rodar as seeds. Mas a seed foi atualizada e hoje de manhã já percebi que não causava mais erros.

**Comment by aleodoni** [comment]
Beleza @wehmhoff. Na verdade esse tipo de problema vai diminuir na medida que o BD sofra menos alterações significativas. É um processo chato até que todas as migrations e seeds fiquem organizadas e agradeço a issue que vc abriu porque me ajuda também a trabalhar para melhorar este processo. Valeu !
