### ISSUE TITLE
[BUG] ERRO 404

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/processo_eletronico#325]
**Descrição do Bug**
Em qualquer tela do sistema, se for pressionado o botão F5 ou selecionada a URL na barra de endereços e se pressionar ENTER, é lançado erro 404 e o sistema se perde na navegação.

**Para Reproduzir**

Passos para reproduzir o bug:
1. Entre em qualquer tela do sistema
2. Aperta F5, ou selecione a URL na barra de endereços e pressione ENTER
3. Veja o erro

**Comportamento Esperado**
A tela deveria ser recarregada pressionando-se F5 ou ENTER na barra de endereços, como em qualquer navegação de site.

</code></pre-->

**Comment by DePorto** [comment]
No proxy reverso do staging:
nginx version: nginx/1.19.4

**Comment by DePorto** [comment]
https://stackoverflow.com/questions/37654727/express-angular-refresh-page-error-404

https://jasonwatmore.com/post/2017/02/24/angular-2-refresh-without-404-in-node-iis

Exemplos de Angular + Node, mas talvez haja alguma correlação com o nosso caso.

**Comment by DePorto** [comment]
Lembrando que os testes iniciais foram feitos com o node rodando localmente, e não da forma como está agora no servidor de staging, que refletirá o futuro ambiente de produção.

**Comment by fderosso** [comment]
Isso não acontecer na máquiina local e nem no inga-desenv, acredito que seja alguma configuração que precisa ser feita no ngnx, pois o inga-desenv é apache

**Comment by brunosoli** [comment]
Resolvido em 8f3b60b.
