### ISSUE TITLE
[BUG] Não é possível criar novo processo no servidor de staging

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/processo_eletronico#326]
**Descrição do Bug**
Não é possível criar um novo processo no sistema.

**Para Reproduzir**

Para criar um processo:
1. * iniciativa interna: ok
2. * tipo : servidor público
3. * matrícula inválida: disparou mensagem de erro, ok
4. * matrícula correta buscou dados:
5. * digitado cpf errado: lançou mensagem de erro: ok
6. * informado e-mail inválido: não lançou erro
7. * gênero: requerimento
8. * Tipo de processo: abono de permanência
9. * mensagem 'recebeu comunicado eltr...' : não

10. => Processo não foi criado. Mensagem de erro "Erro ao inserir processo"

OBS: ** Não se consegue criar um processo com nenhuma mudança de parâmetros, gênero, tipo de processo, etc.

**Comportamento Esperado**
Necessária a criação de novos processos.

**Comment by wehmhoff** [comment]
Esse bug não foi resolvido com a versão de staging e adequações nos containers?
