### ISSUE TITLE
[MELHORIA] Manter histórico dos filtros para busca

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/processo_eletronico#327]
**O que você gostaria de adicionar**:
*Possibilidade de voltar na lista de processos já buscados. 
Quando se entra nos dados de um processo a lista de itens buscados 'some' e uma nova busca sempre é necessária.

**Por que isso é necessário ?**:
Para que não se perca a lista de processos buscados, nem os dados de filtro escolhidos

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**
A necessidade de sempre se inserir os parâmetros de busca para se obter uma determinada lista de processos torna o processo de acesso às informações moroso e complicado.

**Comment by aleodoni** [comment]
@DePorto @wehmhoff 
Implementei o seguinte : 
1. Clicando no botão 'Consultar processos'
![Captura de tela_2020-12-18_11-27-43](https://user-images.githubusercontent.com/12944198/102625871-d8fcb400-4124-11eb-8387-384cad6cc845.png)

2. Os campos marcados em vermelho, manterão os valores de pesquisa durante a navegação evitando assim a necessidade de informá-los novamente:
![Captura de tela_2020-12-18_11-28-08](https://user-images.githubusercontent.com/12944198/102626057-15301480-4125-11eb-9550-2b1b6c22493d.png)

3. Clicando no botão "Pesquisar" o sistema vai para a tela de resultados.
![Captura de tela_2020-12-18_11-28-28](https://user-images.githubusercontent.com/12944198/102627132-7d332a80-4126-11eb-87cb-e35a0be9b950.png)

4. Clicando na lupa, o sistema vai para a tela de detalhes do processo. Adicionei o botão "Voltar à lista" que faz o sistema voltar no item 3 (resultados de pesquisa)
![Captura de tela_2020-12-18_11-28-45](https://user-images.githubusercontent.com/12944198/102627172-90de9100-4126-11eb-92e6-d3faf12ef794.png)

O funcionamento do restante permanece o mesmo.
