### ISSUE TITLE
[BUG] Trâmite permitido mesmo sem arquivo anexado no staging

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/processo_eletronico#328]
**Descrição do Bug**

Ao criar uma manifestação, permitiu trâmite mesmo dando erro ao inserir o arquivo enviado. 
O arquivo da manifestação não foi enviado, mas o botão tramitar ficou disponível e foi possível tramitar o processo sem anexo. 

Funcionaram os filtros de tipo (extensão e tamanho - até 5MB): ok

**Para Reproduzir**

1. Abra um processo que esteja em sua lotação;
2. vá na manifestação;
3. inclua uma nova;
4. indique um arquivo para enviar (dê nome, etc.);
5. no servidor de staging o arquivo não é enviado;
6. mesmo assim o botão TRAMITAR aparece;
7. tramite o processo;
8. veja na página de busca o processo com amanifestação sem arquivo.

**Comportamento Esperado**

Que a manifestação só possa ser encaminhada com no mínimo um arquivo anexado;

</code></pre-->

**Screenshots**

![spae_manif_sem_arq](https://user-images.githubusercontent.com/20687716/99077387-70596f00-259b-11eb-9f4a-9d83649daf2a.png)

**Comment by brunosoli** [comment]
Ao reproduzir o problema aparecem os erros 401 seguido de 500 no log. Trecho relevante:

```
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:02:29 | GET | /spae-api/anexo-manifestacao/278/2020 | 401 | 0.897 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:02:44 | POST | /spae-api/anexo-manifestacao/278/2020 | 500 | 5.368 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | TypeError: Cannot read property 'call' of undefined
spae_backend.1.596yi8n2g6e7@staging    |     at /opt/spae-api/dist/app.js:80:40
spae_backend.1.596yi8n2g6e7@staging    |     at newFn (/opt/spae-api/node_modules/express-async-errors/index.js:16:20)
spae_backend.1.596yi8n2g6e7@staging    |     at Layer.handle_error (/opt/spae-api/node_modules/express/lib/router/layer.js:71:5)
spae_backend.1.596yi8n2g6e7@staging    |     at trim_prefix (/opt/spae-api/node_modules/express/lib/router/index.js:315:13)
spae_backend.1.596yi8n2g6e7@staging    |     at /opt/spae-api/node_modules/express/lib/router/index.js:284:7
spae_backend.1.596yi8n2g6e7@staging    |     at Function.process_params (/opt/spae-api/node_modules/express/lib/router/index.js:335:12)
spae_backend.1.596yi8n2g6e7@staging    |     at next (/opt/spae-api/node_modules/express/lib/router/index.js:275:10)
spae_backend.1.596yi8n2g6e7@staging    |     at /opt/spae-api/node_modules/express/lib/router/index.js:635:15
spae_backend.1.596yi8n2g6e7@staging    |     at next (/opt/spae-api/node_modules/express/lib/router/index.js:260:14)
spae_backend.1.596yi8n2g6e7@staging    |     at next (/opt/spae-api/node_modules/express/lib/router/route.js:127:14)
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:02:44 | GET | /spae-api/manifestacao-processo/278 | 304 | 16.161 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:02:44 | GET | /spae-api/arquivos-manifestacao/1111 | 304 | 7.121 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:08:07 | GET | /spae-api/anexo-manifestacao/278/2020 | 401 | 0.827 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:08:37 | POST | /spae-api/anexo-manifestacao/278/2020 | 500 | 6.273 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | TypeError: Cannot read property 'call' of undefined
spae_backend.1.596yi8n2g6e7@staging    |     at /opt/spae-api/dist/app.js:80:40
spae_backend.1.596yi8n2g6e7@staging    |     at newFn (/opt/spae-api/node_modules/express-async-errors/index.js:16:20)
spae_backend.1.596yi8n2g6e7@staging    |     at Layer.handle_error (/opt/spae-api/node_modules/express/lib/router/layer.js:71:5)
spae_backend.1.596yi8n2g6e7@staging    |     at trim_prefix (/opt/spae-api/node_modules/express/lib/router/index.js:315:13)
spae_backend.1.596yi8n2g6e7@staging    |     at /opt/spae-api/node_modules/express/lib/router/index.js:284:7
spae_backend.1.596yi8n2g6e7@staging    |     at Function.process_params (/opt/spae-api/node_modules/express/lib/router/index.js:335:12)
spae_backend.1.596yi8n2g6e7@staging    |     at next (/opt/spae-api/node_modules/express/lib/router/index.js:275:10)
spae_backend.1.596yi8n2g6e7@staging    |     at /opt/spae-api/node_modules/express/lib/router/index.js:635:15
spae_backend.1.596yi8n2g6e7@staging    |     at next (/opt/spae-api/node_modules/express/lib/router/index.js:260:14)
spae_backend.1.596yi8n2g6e7@staging    |     at next (/opt/spae-api/node_modules/express/lib/router/route.js:127:14)
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:08:37 | GET | /spae-api/manifestacao-processo/278 | 304 | 13.873 ms
spae_backend.1.596yi8n2g6e7@staging    | 
spae_backend.1.596yi8n2g6e7@staging    | info | 18/11/2020 17:08:37 | GET | /spae-api/arquivos-manifestacao/1111 | 304 | 7.107 ms
spae_backend.1.596yi8n2g6e7@staging    | 
```

**Comment by fderosso** [comment]
Nas máquinas locais minha e do Geraldo e no desenv não acontece isso, tem que ficar atento para o seguinte:
1) O processo foi criado localmente na máquina X, então a máquina Y não vai conseguir gravar a manifestação, pois não tem a pasta, a possível solução seria como padrão as máquinas apontarem para uma pasta link default, como é feito no SPL.
2) No .env do backend tem que verificar se o caminho de gravação está correto.

**Comment by fderosso** [comment]
Corrigido da seguinte maneira: se não conseguir gravar o arquivo de manifestação, remove os arquivos e a manifestação correspondente. Como foi uma alteração de várias telas, seria necessário testar com todos os tipos de processo, pois só foi testado com o processo de folha de pagamento.

**Comment by fderosso** [comment]
Commitado, se após os testes ocorrer problema, abrir outra issue.

**Comment by DePorto** [comment]
ok.

**Comment by brunosoli** [comment]
> Corrigido da seguinte maneira: se não conseguir gravar o arquivo de manifestação, remove os arquivos e a manifestação correspondente. Como foi uma alteração de várias telas, seria necessário testar com todos os tipos de processo, pois só foi testado com o processo de folha de pagamento.

Não entendi bem.

Supondo um cenário onde o filesystem esteja, por exemplo, no storage de rede ou em uma nuvem qualquer. Se na tentativa de salvar o arquivo o filesystem esteja indisponível (caiu a rede, por exemplo), na sequência o sistema vai tentar remover arquivos?

----

Apenas para constar e esclarecer o problema inicial: não era uma questão de código (talvez apenas de melhor tratamento do erro, mas não era um problema em si), mas sim de inconsistência de arquivos no filesystem. Haviam processos, trâmites e anexos cadastrados no banco mas não haviam esquema de subpastas e arquivos correspondentes no filesystem. Isso ocorreu porque os testes estavam sendo realizados em servidores diferentes.

**Comment by DePorto** [comment]
De toda sorte é preciso o tratamento do erro de indisponibilidade dos arquivos.

**Comment by fderosso** [comment]
O que acontece é o seguinte: como um filesystem nao esta numa transação de
bd, então foi corrigido assim: o sistema grava primeiro no banco a
manifestação e o arquivo, depois tenta gravar no filesystem, se nao
conseguir gravar o arquivo (catch de resposta de erro) ele desfaz a
gravacao no banco do arquivo e da manifestacao, voltando ao estado inicial.
Em condições normais de funcionamento esse procedimento não é para
acontecer, mas se acontecer é necessário para manter a integridade, não
deixando manifestações e arquivos do banco sem seus respectivos arquivos
fisicos.

Em Sex, 20 de nov de 2020 12:01, De Porto <notifications@github.com>
escreveu:
