### ISSUE TITLE
[MELHORIA] Tratar nomes dos arquivos anexados pelos usuários

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/processo_eletronico#329]
**O que você gostaria de adicionar**:

Adicionar algum tipo de conversão (hash) ou sanitização dos nomes de arquivos adicionados pelos usuários a serem salvos no **backend**.

**Por que isso é necessário ?**

Porque muito frequentemente os usuários anexam documentos cujos nomes de arquivos contém caracteres ilegais a nível de SO (normalmente oriundos de anexos enviados por 3os ou baixados da internet).

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Não tenho certeza do formato em uso hoje mas, aparentemente, os arquivos são salvos com um hash + nome do arquivo "as is".

**Contexto Adicional**

O ideal é:

- manter os nomes de arquivos dentro dos caracteres "normais" da tabela ASCII
- evitar caracteres UTF-8
- tomar cuidado especial com caracteres do tipo `\n`, `\r`, `\0`, etc

Isso evita problemas futuramente também na busca e recuperação de arquivos no backup.

**Comment by wehmhoff** [comment]
Foi tratado durante o desenvolvimento e já está no branch de desenvolvimento

**Comment by brunosoli** [comment]
Ainda acho um design não muito bom o usuário poder intervir no formato como o arquivo é salvo por baixo dos panos: sistemas operacionais e sistemas de arquivos diferentes tem restrições diferentes de nome de arquivo.

**Comment by aleodoni** [comment]
Pensando mais pra frente no esquema do CDN, acho que a gente precisa conversar melhor o esquema de criar diretórios, etc, pois isso pode não ser possível no CDN.
O ideal na minha opinião é **o sistema gerar um nome para o arquivo** e caso necessário, guardar o nome que o usuário deu (fazendo o tratamento) apenas para referência.
Aí a gente esquece a criação de diretórios, etc. Todos os arquivo ficam num só local. Isso facilita muito depois pra implementarmos a gravação e recuperação no CDN.
