### ISSUE TITLE
[MELHORIA] Tratamento de HTTP e HTTPS em ambiente dev/prod

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#338]
**O que você gostaria de adicionar**:

Fazer o tratamento e uso otimizado dos servidores/protocolos HTTP e HTTPS dependendo do ambiente

**Por que isso é necessário ?**:

Facilitar a configuração da aplicação para ambiente de desenvolvimento e garantir que a mesma rode de maneira correta no ambiente de produção.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Assim, não será preciso comentar linhas do servidor ou configurar certificados para rodar a aplicação no ambiente de desenvolvimento. 

**Contexto Adicional**

- Em ambiente de desenvolvimento a aplicação rodará usando o protocolo http
- Em ambiente de produção a aplicação rodará usando protocolo https

**Comment by aleodoni** [comment]
@wehmhoff @brunosoli , estou citando vcs aqui, para receberem a notificação e ficarem a par.
Testado e OK.

Criei um diretório **factories** na raiz do projeto. Nesse diretório, criei um diretório **server** com as factories do servidor.
Antes, ele criava um servidor http e https. Agora, dependendo da variável de ambiente **process.env.NODE_ENV** ele cria ou um servidor https (se essa variável for production) ou um servidor http (se essa variável for qqr outra coisa, por exemplo development, test).
Facilita o desenvolvimento, pois não precisamos dos certificados ou comentar linhas e também em produção, deixando somente o servidor seguro ativo.

**Comment by brunosoli** [comment]
E a issue #295?

Minha sugestão era deixar apenas uma porta aberta (3002) e gerenciar a conexão segura fora da aplicação. Podemos adicionar no [docker-compose.yml](../blob/develop/backend/docker-compose.yml) um container do nginx para simplificar o desenvolvimento.

Outro problema é que, usando certificado no backend, precisamos dessa informação em tempo de build dos contêineres o que inviabiliza o build automático.

O que vocês acham?

**Comment by aleodoni** [comment]
Acho ainda melhor. O legal de usar factory é que fazendo essa alteração, a gente apenas ajusta a factory pai e não precisa acertar o resto.
Podemos programar essas alterações para esta semana (milestone 36)
