### ISSUE TITLE
[DOC] Fluxos - Movimentações: Apresentação

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/processo_eletronico#34]
**Descrição da issue**

Os fluxos do processo devem ser apresentados numa tela de rolagem vertical, com movimentações numeradas em ordem crescente, estando as movimentações (fluxos / nós) mais recentes por primeiro na listagem.

**Exemplo de uso**
Imagem anexa de tela de visualização dos dados de um processo no PROJUDI:

![modelo_fluxo_movimentacoes_projudi](https://user-images.githubusercontent.com/20687716/79185539-8e84a400-7ded-11ea-8cf6-48b6e8d93504.png)

**Comment by brunosoli** [comment]
Isso não deveria ser estar como melhoria no frontend?

**Comment by aleodoni** [comment]
> Isso não deveria ser estar como melhoria no frontend?

Acho que sim, @brunosoli. Deveria ser criada uma issue mais completa a respeito com todos os requisitos desta tela, como por exemplo ordenação inicial, descrição completa dos campos, permissões, etc.
Provavelmente afetaria tanto o frontend (apresentação) quanto o backend (controller que retorna estas informações). De cabeça não sei se o backend para isso já foi implementado.
