### ISSUE TITLE
[DISCUSSÃO] Diminuir o acoplamento com o banco de dados

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#347]
Atualmente, o backend do sistema está fortemente acoplado com o banco de dados devido principalmente à utilização do dblink (https://www.postgresql.org/docs/12/contrib-dblink-function.html), responsável hoje por buscar informações de sistemas terceiros.

Uma sugestão para resolver este problema seria a criação de uma api para conversar com estes sistemas, retornando as informações necessárias.

Vantagens desta solução:

- Transparência: Para o SPAe, fica transparente o consumo das informações, sendo necessário apenas efetuar chamadas para esta api.
- Manutenção: A maioria das alterações são feitas na api, sendo desnecessária a alteração (na maioria dos casos) no SPAe.
- Facilidade de criar e manter o ambiente de desenvolvimento: Pode-se facilmente criar uma api fake (https://github.com/typicode/json-server) para simular o funcionamento da mesma.
- Permitir CI (Integração Contínua) em servidores remotos: Utilizando a api fake, pode-se rodar os testes e migrations em qualquer lugar.
- Disponibilidade: Pode-se implementar funcionalidade de cache (Redis por exemplo) para garantir que o SPAe funcione mesmo que a aplicação terceira (ou seu BD) estejam fora do ar
- Performance: Utilizando em conjunto com o item anterior, mais de uma instância da api com balanceamento de carga.

Fica em aberto para discutirmos aqui outras soluções.

**Comment by DePorto** [comment]
Inclusive essa API será necessária pois estamos em processo de licitação para contratar novo software de gestão. Então será totalmente necessário que este serviço esteja ok no processo de aceite e adequação da nova solução ao ambiente da CMC.

**Comment by DePorto** [comment]
Acredito que para elaborarmos a API precisamos validar quais views e tabelas são ainda necessárias e que tenham conexão com informações do sistema de contabilidade. Geraldo e eu verificamos que há tabelas e views na base que não são mais usadas, e poderiam ser excluídas. Após essa limpeza, pode-se levantar quais são os dados que o SPAe consome dos sistemas de gestão (RH e Contab). Basicamente pelo que pudemos apurar são dados relacionados a informações de usuários, setores do organograma (da parte do RH) e dados de fornecedores e de empenhos (para a parte de execução de despesas e pronto pagamento, etc.)

**Comment by aleodoni** [comment]
Perfeito. O próximo passo seria que todos os envolvidos dessem aqui o ack para que possamos bater o martelo nessa solução (ou em outra proposta) para encerrarmos essa issue e criarmos uma issue para a construção da api em si.

**Comment by aleodoni** [comment]
Claro, deve-se definir cronograma e contexto para a mesma.

**Comment by wehmhoff** [comment]
De acordo.

**Comment by brunosoli** [comment]
De acordo. E além dos pontos que o Alexandre citou, esse dblink também inviabiliza o build automático da imagem docker do backend.

Outro ponto é que consideramos que os dados vindos do software de gestão são sempre consistentes (ou seja, desconsideramos os "testes" que o pessoal do RH fica fazendo com as lotações e ativações/desativações de usuários).

**Comment by aleodoni** [comment]
Legal. Para eu poder fechar esta issue, seria interessante receber aqui o OK do @rodrigoferraro ou do @DePorto só para que conste que a chefia está de acordo com o definido.

**Comment by DePorto** [comment]
Ok, de acordo.
