### ISSUE TITLE
[MELHORIA] Integrar seeds de LDAP e banco

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/processo_eletronico#44]
**O que você gostaria de adicionar**:
Integrar os seeds de usuários e lotações no banco. Mais especificamente, os usuários precisam ser os mesmos nos arquivos:

https://github.com/CMCuritiba/processo_eletronico/blob/086ac17e70152c4916df4da7d62324ee9cf9b8f7/backend/ldap-seeds.ldif#L308

https://github.com/CMCuritiba/processo_eletronico/blob/086ac17e70152c4916df4da7d62324ee9cf9b8f7/backend/src/database/seeds/20200403190712-lotacao.js#L11

**Por que isso é necessário?**:
Enquanto a autorização é realizada consultando o banco, é importante que os seeds de usuários e suas lotações estejam integradas. Isto facilita o desenvolvimento e evita frustrações no primeiro uso da aplicação.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**
Não.

**Contexto Adicional**
Nenhum.

**Comment by aleodoni** [comment]
Acho que seria legal quem fizer o clone e rodar a aplicação localmente já atualizar o LDAP e os seeds (esse eu acho que já está ok) com o seu usuário.

**Comment by brunosoli** [comment]
O merge #49 garante que o login funcione localmente no primeiro clone mas, como comentei no request, manter os usuários nestas duas bases é frágil.
