### ISSUE TITLE
[DOC] Don't hard-code

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/processo_eletronico#46]
**O que você gostaria de adicionar**:
Sugestão de padrão de código a se adotar.

Regra de ouro: **separar código dos dados**

Ou seja, não coloque strings hard-coded nas suas funções.

**Por que isso é necessário ?**:

1. Facilitar busca e acesso à informação;
1. Evitar retrabalho;
1. Padroniza e deixa o código elegante;
1. Permite que o texto seja traduzido

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**
Ainda não.

**Contexto Adicional**
Além de informação e texto, há muitos parâmetros de sistema que também estão hard-coded.A issue #40 é um exemplo. Talvez seja melhor abrir uma issue para a revisão geral.

**Comment by aleodoni** [comment]
Vou colocar isso como documentação porque não dá pra gente "fechar" essa issue, e acho que assim ela fica melhor categorizada.

**Comment by DePorto** [comment]
Acredito ainda que esta questão deve ser movida para discussão em outro metaprojeto, como o do Guia de Boas Práticas de JS , ou de um guia maior, de método de desenvolvimento.

Trouxe a discussão para cá: https://github.com/orgs/CMCuritiba/projects/3
