### ISSUE TITLE
[MELHORIA] Remover confirmação pra sair

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/processo_eletronico#48]
**O que você gostaria de adicionar**:
Remover o diálogo "Deseja realmente sair do sistema?" ao clicar em sair.

A sessão é permanente entre fechamento e aberturas de janela/aba do navegador, correto? Isto já é o suficiente, se o usuário clicou em sair e depois mudar de ideia ele pode refazer o login.

O diálogo mais estorva do que ajuda.

**Por que isso é necessário?**:
Cite 3 serviços online que você utiliza que te perguntam se você tem certeza que deseja sair.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**
Não.

**Contexto Adicional**
Não.

**Comment by fderosso** [comment]
Removido.
