### ISSUE TITLE
[MELHORIA] Migration para Tabela Genero

### ISSUE THREAD

**Issue by rodrigoferraro** [CMCuritiba/processo_eletronico#59]
**O que você gostaria de adicionar**:
Adicionar migration para a tabela Genero.

**Por que isso é necessário ?**:
Para usufruir efetivamente das vantagens de usar containers desacoplados.

Para o melhor funcionamento do docker postgres sem necessidade de rodar atualizações de SQL.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**
Eu acho que perdi alguma das atualizações que @fderosso passou e quando fui abrir a tela de processo, não me permitia prosseguir porque não encontrava [Genero] para alimentar a respectiva combobox.

Eu sempre fico frustrado quando as coisas não dão certo! rsrs. Mentira, não fico não! Sou positivo!
Só estou tentando ajudar.

**Comment by aleodoni** [comment]
@rodrigoferraro, coloquei você como o cara que vai fazer isso, beleza?
Outra coisa: A gente está criando um milestone por semana, então veja se essa task você consegue finalizar no Milestone 4 ou no da semana que vem (aí teria que criar o Milestone 5 com a data para 01/05).
Qualquer coisa, me avise.
