### ISSUE TITLE
[MELHORIA] Migrations e seeds para objetos do database que ainda não os tenha

### ISSUE THREAD

**Issue by rodrigoferraro** [CMCuritiba/processo_eletronico#66]
**O que você gostaria de adicionar**:
Migration e seed para os objetos do database que ainda não os tenha.

**Por que isso é necessário ?**:
Para poder rodar a aplicação em desenvolvimento sem ter de restaurar o backup do banco.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**
Não. 

**Contexto Adicional**
Procurando melhorar nossas práticas de desenvolvimento, precisamos adotar efetivamente a utilização de migrations para objetos do banco.
Toda aplicação, a partir de 2020, deve utilizar migrations para criar os objetos de banco de dados.

Considerando que é nosso desejo aumentar nossa contribuição na comunidade de software livre e, entendendo que para contribuir e colaborar é preciso seguir padrões de boas práticas globais.
Considerando que é nosso desejo o maior envolvimento de outros membros da equipe e, entendendo que para facilitar/atrair o envolvimento de outros é preciso seguir padrões de boas práticas globais.

**Comment by rodrigoferraro** [comment]
@fderosso, a view area usa esta outra view na consulta (v_cmclotacaousuario) que não tenho no banco. Você pode me passar pra eu criar aqui, por gentileza. Pode ser no email pra não ficar extenso aqui.

**Comment by aleodoni** [comment]
Vou fechar essa issue, pois devemos abrir uma issue para cada conjunto de tabelas/views/functions/etc que fazem parte de uma tela específica. Caso contrário teremos uma issue muito grande e com tempo de execução muito grande.

**Comment by rodrigoferraro** [comment]
@aleodoni, você deletou o branch associado a ela?
