### ISSUE TITLE
[MELHORIA]Criação de tela de tipo de documento

### ISSUE THREAD

**Issue by fderosso** [CMCuritiba/processo_eletronico#69]
Criar a tela de crud de tipo de documento para a manifestação.

**Por que isso é necessário ?**:
Pedido do usuário para ter mais controle nas manifestações.

**Contexto Adicional**
- Criando também as migrations e seeders.

**Comment by fderosso** [comment]
Criado o crud de tipos de documento, com migrations e seeders, também retirado model que não era mais usado.

**Comment by rodrigoferraro** [comment]
esta issue fechou com este [commit](https://github.com/CMCuritiba/processo_eletronico/commit/285ac2fc698d3ed88132b06584bfa4d262a5ca74)
