### ISSUE TITLE
[MELHORIA] Migration para view utilizada nas telas de processo e manifestações

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/processo_eletronico#81]
**O que você gostaria de adicionar**:

Migration para criar a view utilizadas nas telas de criação de processos, auxiliar de consulta de processos e de manifestações.

**Por que isso é necessário ?**:
Já foi feita a refatoração destas telas, e criada uma nova view que é utilizada nas mesmas.

**Sua melhoria está relacionada com algum problema no sistema ? Descreva**

Não

**Contexto Adicional**

```sql
CREATE OR REPLACE VIEW spa2.v_area_combo AS
SELECT "Setor".set_id,
"Setor".set_nome,
"Setor".set_tipo
FROM spa2.setor "Setor"
WHERE "Setor".set_id = "Setor".set_id_area
ORDER BY "Setor".set_nome;

ALTER TABLE spa2.v_area_combo
OWNER TO spa2;
GRANT ALL ON TABLE spa2.v_area_combo TO spa2;
GRANT ALL ON TABLE spa2.v_area_combo TO "usuario.spa2";
```

**Comment by aleodoni** [comment]
@rodrigoferraro , moveu para a coluna Done e não fechou a issue ? Precisa fechar a issue antes de move-la para esta coluna, senão a gente se perde no controle.

**Comment by rodrigoferraro** [comment]
Eu achei que concluindo a programação iria para Done e só a fecharia após "homologação".
Mas se for pra fechar, eu fecho.

**Comment by aleodoni** [comment]
@rodrigoferraro, como não temos ninguém disponível para homologar no momento, as issues são fechadas e caso apareça algum erro, reabrimos a issue. Além disso, se a issue não é fechada, não recebemos nenhum aviso de conclusão da mesma; ela simplesmente desaparece da aba "In Progress" e vai para a aba "Done". Concorda comigo que fica meio difícil manter um "tracking" das coisas desse jeito, certo ?
Então o correto é fechar a issue, passar para a aba "Done". Todos envolvidos recebem a notificação que a issue foi fechada e aí, caso essa issue tenha algum erro, reabrimos a mesma para que seja corrigida.
