### ISSUE TITLE
[MELHORIA]Criar componente de input com máscara para código de processo

### ISSUE THREAD

**Issue by fderosso** [CMCuritiba/processo_eletronico#90]
Criar um componente do tipo input -> text, para o código do processo.

**Por que isso é necessário ?**:

Necessário para uma maior agilidade na localização do processo.

**Contexto Adicional**

- O padrão do campo(string no banco) é número(com zeros à esquerda) barra ano: 00000/0000 Ex: 00062/2020

- Geralmente o usuário está acostumado a digitar o número sem zeros à esquerda e quando digitar a barra ele automaticamente completa com os zeros à esquerda, posicionando o cursor logo após a barra, para preenchimento do ano.

**Comment by aleodoni** [comment]
Componente deve ser usado dentro do formulário unform e ser usado como qualquer outro componente input .
Funcionamento: 
- O componente aceita somente campo no formato 99999/9999
- Digitando '/' no componente, ele formata os 5 primeiros dígitos do número do processo: por exemplo: se o usuário digitar 1/, o componente transforma em 00001/
